### PR TITLE
Added support for TS-XW Racer wheel

### PR DESCRIPTION
**Pull request by simon50keda**
As I got the mentioned wheel, I was able to prepare configuration to work with the tmdrv.

### CODE REVIEW

**Comment by leillo1975** [comment]
Hello @simon50keda , I don't know if this is alive, but there are the same project on gitlab and seem to be more updated:
https://gitlab.com/her0/tmdrv

Greetings

**Comment by simon50keda** [comment]
Well for now I'm not on GitLab, so can you notify author there? Maybe he will pick it up ;)

**Comment by leillo1975** [comment]
No problem
https://gitlab.com/her0/tmdrv/issues/19

**Comment by her001** [comment]
Hey, sorry I didn't get to this until now. With the pandemic, I just hadn't gotten around to it, as I have been very busy with work.

Thank you very much for the contribution!

**Pull request merged**
